version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: kingsmove-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: kingsmove
    volumes:
      - mongodb_data:/data/db
    networks:
      - kingsmove-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: kingsmove-backend
    restart: unless-stopped
    ports:
      - "4000:4000"
      - "4001:4001"
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/kingsmove?authSource=admin
      PORT: 4000
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - kingsmove-network
    command: npm run dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: kingsmove-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      VITE_BACKEND_URL: http://localhost:4000
      SOCKET_URL: http://localhost:4001
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - kingsmove-network
    command: npm run dev

volumes:
  mongodb_data:

networks:
  kingsmove-network:
    driver: bridge